# PS5: Đánh giá Hiệu quả Hoạt động của Văn phòng và Đại lý theo Địa bàn

**Mục tiêu:** So sánh hiệu quả kinh doanh giữa các văn phòng hoặc đại lý nhằm tối ưu hóa mạng lưới phân phối và nâng cao hiệu quả khai thác thị trường.

## Cách tiếp cận phân tích
1. **Phần 1:** Suy ra danh sách Văn phòng và Đại lý từ mức độ tập trung khách hàng theo District.
2. **Phần 2:** Thống kê doanh thu, số hóa đơn và khách hàng phục vụ của từng đơn vị.
3. **Phần 3:** Tính doanh thu bình quân trên khách hàng và hóa đơn (Hiệu suất kinh doanh).
4. **Phần 4:** So sánh hiệu quả hoạt động giữa các văn phòng trong cùng Region hoặc City.
5. **Phần 5:** Xếp hạng theo điểm tổng hợp KPI và phân nhóm đơn vị (Hiệu quả cao / Ổn định / Cần cải thiện).
6. **Phần 6:** Đề xuất giải pháp chiến lược tối ưu hóa mạng lưới phân phối và xuất dữ liệu Data Mart.

## Quy ước suy ra đơn vị
Dataset không có mã văn phòng/đại lý thực tế, nên bài phân tích áp dụng quy ước thực tiễn:
- **Văn phòng trung tâm:** District có số lượng khách hàng đông nhất (Hạng 1) trong mỗi City.
- **Đại lý:** Các District còn lại có percentile số khách hàng từ 85% trở lên trong City (Top 15% địa bàn đông khách nhất).
- Mỗi District chỉ đại diện cho một đơn vị duy nhất để tránh việc trùng lặp doanh số giữa văn phòng và đại lý.

## Chuẩn bị thư viện và dữ liệu Silver

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_theme(style="whitegrid")
pd.options.display.float_format = "{:,.2f}".format

customers = pd.read_csv("../../SilverData/customers_silver.csv")
geography = pd.read_csv("../../SilverData/geography_silver.csv")
orders = pd.read_csv("../../SilverData/orders_silver.csv")
payments = pd.read_csv("../../SilverData/payments_silver.csv")
returns = pd.read_csv("../../SilverData/returns_silver.csv")

print("Dữ liệu nạp thành công:")
print("Customers:", customers.shape)
print("Geography:", geography.shape)
print("Orders   :", orders.shape)
print("Payments :", payments.shape)
print("Returns  :", returns.shape)

Dữ liệu nạp thành công:
Customers: (121930, 6)
Geography: (39948, 4)
Orders   : (646945, 9)
Payments : (646945, 4)
Returns  : (39939, 7)

# Phần 1: Xác định danh sách văn phòng và đại lý

Khách hàng được ánh xạ vào địa giới qua `zip`. Mỗi địa bàn được định danh duy nhất bằng cụm `Region + City + District`.

Trong mỗi City:
- District đứng hạng 1 về số lượng khách hàng được xác định là **Văn phòng trung tâm**.
- Các District còn lại có percentile từ 85 trở lên (Top 15% khách hàng) được xác định là **Đại lý**.

In [51]:
# Ghép khách hàng với địa giới
customer_location = customers.merge(geography, on="zip", how="left")

# Đếm số khách hàng theo District
customer_by_district = (
    customer_location
    .groupby(["region", "city", "district"], as_index=False)
    .agg(total_customers=("customer_id", "nunique"))
)

# Tính percentile và thứ hạng khách trong từng City
customer_by_district["customer_percentile_in_city"] = (
    customer_by_district
    .groupby(["region", "city"])["total_customers"]
    .rank(method="average", pct=True)
)

customer_by_district["customer_rank_in_city"] = (
    customer_by_district
    .groupby(["region", "city"])["total_customers"]
    .rank(method="first", ascending=False)
)

# Lọc nhóm 15% đông khách nhất
candidate_units = customer_by_district.loc[
    customer_by_district["customer_percentile_in_city"] >= 0.85
].copy()

# Gán loại đơn vị
candidate_units["unit_type"] = "Đại lý"
candidate_units.loc[candidate_units["customer_rank_in_city"] == 1, "unit_type"] = "Văn phòng"
candidate_units["unit_id"] = (
    candidate_units["unit_type"] + " | " + candidate_units["region"] + " | " + candidate_units["city"] + " | " + candidate_units["district"]
)

candidate_units = candidate_units.sort_values(["region", "city", "customer_rank_in_city"]).reset_index(drop=True)

print("Tổng số đơn vị suy ra:", len(candidate_units))
print("- Văn phòng:", (candidate_units["unit_type"] == "Văn phòng").sum())
print("- Đại lý   :", (candidate_units["unit_type"] == "Đại lý").sum())
display(candidate_units.head(10))

Tổng số đơn vị suy ra: 98
- Văn phòng: 42
- Đại lý   : 56

,region,city,district,total_customers,customer_percentile_in_city,customer_rank_in_city,unit_type,unit_id
0,Central,Da Nang,District #25,488,1.00,1.00,Văn phòng,Văn phòng | Central | Da Nang | District #25
1,Central,Da Nang,District #30,396,0.92,2.00,Đại lý,Đại lý | Central | Da Nang | District #30
2,Central,Dong Hoi,District #21,442,1.00,1.00,Văn phòng,Văn phòng | Central | Dong Hoi | District #21
3,Central,Dong Hoi,District #24,435,0.92,2.00,Đại lý,Đại lý | Central | Dong Hoi | District #24
4,Central,Hoi An,District #24,410,1.00,1.00,Văn phòng,Văn phòng | Central | Hoi An | District #24
5,Central,Hoi An,District #21,409,0.92,2.00,Đại lý,Đại lý | Central | Hoi An | District #21
6,Central,Hue,District #24,419,1.00,1.00,Văn phòng,Văn phòng | Central | Hue | District #24
7,Central,Hue,District #25,414,0.92,2.00,Đại lý,Đại lý | Central | Hue | District #25
8,Central,Kon Tum,District #25,428,1.00,1.00,Văn phòng,Văn phòng | Central | Kon Tum | District #25
9,Central,Kon Tum,District #24,385,0.92,2.00,Đại lý,Đại lý | Central | Kon Tum | District #24

## Chuẩn bị dữ liệu doanh thu thuần cho từng đơn hàng

- Chỉ lấy các đơn có trạng thái `delivered` (đã giao) và `returned` (đã trả hàng).
- Loại bỏ các đơn `returned` nhưng thiếu dữ liệu hoàn tiền.
- Doanh thu thuần = `payment_value` - `total_refund`.

In [52]:
refund_by_order = (
    returns.groupby("order_id", as_index=False)
    .agg(total_refund=("refund_amount", "sum"))
)

df = orders.merge(geography, on="zip", how="left")
df = df.merge(payments, on="order_id", how="left")
df = df.merge(refund_by_order, on="order_id", how="left")

# Lấy đơn delivered và returned
df_revenue = df.loc[df["order_status"].isin(["delivered", "returned"])].copy()

# Lọc bỏ đơn returned thiếu tiền hoàn
missing_refund = (df_revenue["order_status"] == "returned") & df_revenue["total_refund"].isna()
df_revenue_valid = df_revenue.loc[~missing_refund].copy()

df_revenue_valid["total_refund"] = df_revenue_valid["total_refund"].fillna(0)
df_revenue_valid["net_revenue"] = df_revenue_valid["payment_value"] - df_revenue_valid["total_refund"]

print("Số đơn hợp lệ dùng phân tích:", len(df_revenue_valid))
print("Tổng doanh thu thuần: {:,.2f}".format(df_revenue_valid["net_revenue"].sum()))

Số đơn hợp lệ dùng phân tích: 552778
Tổng doanh thu thuần: 12,871,731,922.00

# Phần 2: Thống kê doanh thu, hóa đơn và khách hàng phục vụ

Thống kê hoạt động kinh doanh cho danh sách 98 điểm văn phòng và đại lý đã xác định ở Phần 1.

In [53]:
# Tổng hợp theo District từ dữ liệu đơn hàng
district_business = (
    df_revenue_valid
    .groupby(["region", "city", "district"], as_index=False)
    .agg(
        gross_revenue=("payment_value", "sum"),
        refund_amount=("total_refund", "sum"),
        net_revenue=("net_revenue", "sum"),
        invoice_count=("order_id", "nunique"),
        served_customers=("customer_id", "nunique")
    )
)

# Ghép với danh sách 98 đơn vị
unit_kpi = candidate_units.merge(
    district_business,
    on=["region", "city", "district"],
    how="left"
)

cols_fill = ["gross_revenue", "refund_amount", "net_revenue", "invoice_count", "served_customers"]
unit_kpi[cols_fill] = unit_kpi[cols_fill].fillna(0)

display(unit_kpi[["unit_id", "unit_type", "total_customers", "served_customers", "invoice_count", "net_revenue"]].head(10))

,unit_id,unit_type,total_customers,served_customers,invoice_count,net_revenue
0,Văn phòng | Central | Da Nang | District #25,Văn phòng,488,313,1656,"37,518,770.93"
1,Đại lý | Central | Da Nang | District #30,Đại lý,396,232,857,"21,819,945.03"
2,Văn phòng | Central | Dong Hoi | District #21,Văn phòng,442,256,877,"21,114,301.56"
3,Đại lý | Central | Dong Hoi | District #24,Đại lý,435,302,1605,"35,622,643.18"
4,Văn phòng | Central | Hoi An | District #24,Văn phòng,410,286,1510,"33,616,884.44"
5,Đại lý | Central | Hoi An | District #21,Đại lý,409,252,1217,"27,431,899.51"
6,Văn phòng | Central | Hue | District #24,Văn phòng,419,294,1354,"32,238,663.52"
7,Đại lý | Central | Hue | District #25,Đại lý,414,264,1184,"27,989,466.37"
8,Văn phòng | Central | Kon Tum | District #25,Văn phòng,428,272,1246,"29,149,870.67"
9,Đại lý | Central | Kon Tum | District #24,Đại lý,385,279,1487,"34,660,882.37"

# Phần 3: Doanh thu bình quân trên khách hàng và hóa đơn

Các chỉ số hiệu suất bình quân gồm:
- `revenue_per_customer` = `net_revenue` / `served_customers` (Doanh thu bình quân trên khách hàng phục vụ).
- `revenue_per_invoice` = `net_revenue` / `invoice_count` (Giá trị trung bình của mỗi hóa đơn / AOV).
- `customer_activation_pct` = `served_customers` / `total_customers` × 100 (Tỷ lệ khai thác khách hàng tiềm năng).

In [54]:
unit_kpi["revenue_per_customer"] = unit_kpi["net_revenue"] / unit_kpi["served_customers"].replace(0, np.nan)
unit_kpi["revenue_per_invoice"] = unit_kpi["net_revenue"] / unit_kpi["invoice_count"].replace(0, np.nan)
unit_kpi["customer_activation_pct"] = unit_kpi["served_customers"] / unit_kpi["total_customers"] * 100

display(unit_kpi[[
    "unit_id", "net_revenue", "revenue_per_customer", 
    "revenue_per_invoice", "customer_activation_pct"
]].head(10))

,unit_id,net_revenue,revenue_per_customer,revenue_per_invoice,customer_activation_pct
0,Văn phòng | Central | Da Nang | District #25,"37,518,770.93","119,868.28","22,656.26",64.14
1,Đại lý | Central | Da Nang | District #30,"21,819,945.03","94,051.49","25,460.85",58.59
2,Văn phòng | Central | Dong Hoi | District #21,"21,114,301.56","82,477.74","24,075.60",57.92
3,Đại lý | Central | Dong Hoi | District #24,"35,622,643.18","117,955.77","22,194.79",69.43
4,Văn phòng | Central | Hoi An | District #24,"33,616,884.44","117,541.55","22,262.84",69.76
5,Đại lý | Central | Hoi An | District #21,"27,431,899.51","108,856.74","22,540.59",61.61
6,Văn phòng | Central | Hue | District #24,"32,238,663.52","109,655.32","23,809.94",70.17
7,Đại lý | Central | Hue | District #25,"27,989,466.37","106,020.71","23,639.75",63.77
8,Văn phòng | Central | Kon Tum | District #25,"29,149,870.67","107,168.64","23,394.76",63.55
9,Đại lý | Central | Kon Tum | District #24,"34,660,882.37","124,232.55","23,309.27",72.47

# Phần 4: So sánh hiệu quả hoạt động giữa các văn phòng trong cùng Region

So sánh các Văn phòng trung tâm trong cùng một Vùng địa lý về các khía cạnh: Doanh thu thuần, Số khách phục vụ, Doanh thu/hóa đơn và Số lượng hóa đơn.

In [ ]:
office_comparison = unit_kpi.loc[unit_kpi["unit_type"] == "Văn phòng"].copy()


office_comparison["rank_in_region"] = (
    office_comparison.groupby("region")["net_revenue"].rank(method="dense", ascending=False)
)

display(office_comparison[[
    "region", "city", "district", "net_revenue", "served_customers", "rank_in_region"
]].head(15))

,region,city,district,net_revenue,served_customers,rank_in_region
7,East,Viet Tri,District #19,"31,757,608.00",262,6.00
8,East,Lao Cai,District #19,"31,953,442.08",228,4.00
10,Central,Hue,District #24,"32,238,663.52",294,4.00
12,Central,Quang Ngai,District #24,"38,189,634.11",336,1.00
17,East,Hanoi,District #19,"33,265,691.64",284,1.00
18,East,Hai Phong,District #01,"27,961,097.74",256,9.00
20,East,Nam Dinh,District #19,"33,206,904.15",238,2.00
21,Central,Da Nang,District #25,"37,518,770.93",313,2.00
22,East,Son Tay,District #19,"32,432,218.52",286,3.00
23,Central,Hoi An,District #24,"33,616,884.44",286,3.00
24,West,Bac Lieu,District #39,"29,545,030.30",151,6.00
26,West,Bien Hoa,District #33,"35,510,102.38",178,2.00
27,East,Bac Giang,District #19,"30,079,105.38",257,8.00
29,West,Ho Chi Minh City,District #33,"36,955,784.76",205,1.00
30,East,Phu Ly,District #19,"31,788,724.78",290,5.00

# Phần 5: Xếp hạng KPI tổng hợp và phân nhóm đơn vị

Điểm KPI tổng hợp (`kpi_score`) từ 0 đến 100 được tính bằng trung bình thứ hạng phần trăm của 5 chỉ số cốt lõi:
1. Doanh thu thuần (`net_revenue`)
2. Số khách hàng phục vụ (`served_customers`)
3. Doanh thu bình quân trên khách hàng (`revenue_per_customer`)
4. Doanh thu bình quân trên hóa đơn (`revenue_per_invoice`)
5. Tỷ lệ khai thác khách hàng tiềm năng (`customer_activation_pct`)

Dựa vào tứ phân vị (Q1 25% và Q3 75%), các đơn vị được chia thành 3 nhóm:
- **Hiệu quả cao:** Điểm KPI thuộc Top 25% cao nhất (>= Q3).
- **Hoạt động ổn định:** Điểm KPI nằm trong khoảng 50% trung vị (Q1 đến Q3).
- **Cần cải thiện:** Điểm KPI thuộc nhóm 25% thấp nhất (<= Q1).

In [61]:
kpi_columns = [
    "net_revenue", "served_customers", "revenue_per_customer",
    "revenue_per_invoice", "customer_activation_pct"
]

# Chấm điểm percentile 5 chỉ số
for col in kpi_columns:
    unit_kpi[col + "_score"] = unit_kpi[col].rank(pct=True)

score_cols = [c + "_score" for c in kpi_columns]
unit_kpi["kpi_score"] = unit_kpi[score_cols].mean(axis=1) * 100
unit_kpi = unit_kpi.sort_values("kpi_score", ascending=False).reset_index(drop=True)
unit_kpi["overall_rank"] = range(1, len(unit_kpi) + 1)

# Phân nhóm theo tứ phân vị (Q1 25%, Q3 75%)
q1 = unit_kpi["kpi_score"].quantile(0.25)
q3 = unit_kpi["kpi_score"].quantile(0.75)

unit_kpi["performance_group"] = "Hoạt động ổn định"
unit_kpi.loc[unit_kpi["kpi_score"] >= q3, "performance_group"] = "Hiệu quả cao"
unit_kpi.loc[unit_kpi["kpi_score"] <= q1, "performance_group"] = "Cần cải thiện"

print("Số lượng đơn vị theo nhóm:")
print(unit_kpi["performance_group"].value_counts())
display(unit_kpi[["overall_rank", "unit_id", "unit_type", "net_revenue", "kpi_score", "performance_group"]].head(10))

Số lượng đơn vị theo nhóm:
performance_group
Hoạt động ổn định    48
Hiệu quả cao         25
Cần cải thiện        25
Name: count, dtype: int64

,overall_rank,unit_id,unit_type,net_revenue,kpi_score,performance_group
0,1,Đại lý | East | Ha Long | District #03,Đại lý,"39,481,062.60",88.78,Hiệu quả cao
1,2,Đại lý | East | Phu Ly | District #01,Đại lý,"35,915,060.95",84.08,Hiệu quả cao
2,3,Đại lý | East | Uong Bi | District #09,Đại lý,"39,955,901.77",81.12,Hiệu quả cao
3,4,Đại lý | West | Long Xuyen | District #39,Đại lý,"34,583,746.97",77.35,Hiệu quả cao
4,5,Đại lý | East | Bac Ninh | District #03,Đại lý,"29,468,270.21",76.73,Hiệu quả cao
5,6,Đại lý | Central | Kon Tum | District #24,Đại lý,"34,660,882.37",76.73,Hiệu quả cao
6,7,Đại lý | East | Ninh Binh | District #03,Đại lý,"30,225,979.48",73.47,Hiệu quả cao
7,8,Văn phòng | East | Viet Tri | District #19,Văn phòng,"31,757,608.00",73.16,Hiệu quả cao
8,9,Văn phòng | East | Lao Cai | District #19,Văn phòng,"31,953,442.08",72.24,Hiệu quả cao
9,10,Đại lý | East | Hanoi | District #11,Đại lý,"35,171,108.23",71.22,Hiệu quả cao

# Phần 6: Đề xuất giải pháp chiến lược và Xuất Data Mart

Đề xuất hành động cụ thể cho từng đơn vị dựa trên Nhóm hiệu quả và Tỷ lệ khai thác khách hàng:
- **Ưu tiên mở rộng:** Đơn vị thuộc nhóm *Hiệu quả cao* (Top 25% điểm KPI dẫn đầu).
- **Tăng khai thác khách hàng:** Đơn vị chưa đạt hiệu quả cao nhưng tỷ lệ khai thác khách còn thấp hơn mức trung vị (còn nhiều dư địa tiềm năng).
- **Duy trì và theo dõi:** Đơn vị hoạt động ổn định, tỷ lệ khai thác đạt mức tốt.
- **Khảo sát trước khi tái cơ cấu:** Đơn vị thuộc nhóm *Cần cải thiện* nhưng tỷ lệ khai thác đã bão hòa (cần rà soát chi phí, mặt bằng hoặc chuyển đổi mô hình).

In [63]:
median_activation = unit_kpi["customer_activation_pct"].median()

unit_kpi["recommendation"] = "Duy trì và theo dõi"
unit_kpi.loc[unit_kpi["performance_group"].eq("Hiệu quả cao"), "recommendation"] = "Ưu tiên mở rộng"
unit_kpi.loc[
    ~unit_kpi["performance_group"].eq("Hiệu quả cao") & unit_kpi["customer_activation_pct"].lt(median_activation),
    "recommendation"
] = "Tăng khai thác khách hàng"
unit_kpi.loc[
    unit_kpi["performance_group"].eq("Cần cải thiện") & unit_kpi["customer_activation_pct"].ge(median_activation),
    "recommendation"
] = "Khảo sát trước khi tái cơ cấu"

print("Phân bố số lượng đơn vị theo đề xuất:")
print(unit_kpi["recommendation"].value_counts())

# Xuất kết quả đánh giá đơn vị kinh doanh phục vụ vẽ Dashboard
unit_kpi.to_csv("unit_kpi.csv", index=False)
print("\nĐã xuất thành công file: unit_kpi.csv")

display(unit_kpi[["overall_rank", "unit_id", "unit_type", "net_revenue", "kpi_score", "performance_group", "recommendation"]].head(10))

Phân bố số lượng đơn vị theo đề xuất:
recommendation
Tăng khai thác khách hàng        47
Ưu tiên mở rộng                  25
Duy trì và theo dõi              24
Khảo sát trước khi tái cơ cấu     2
Name: count, dtype: int64

Đã xuất thành công file: GoldData/gold_unit_kpi.csv

,overall_rank,unit_id,unit_type,net_revenue,kpi_score,performance_group,recommendation
0,1,Đại lý | East | Ha Long | District #03,Đại lý,"39,481,062.60",88.78,Hiệu quả cao,Ưu tiên mở rộng
1,2,Đại lý | East | Phu Ly | District #01,Đại lý,"35,915,060.95",84.08,Hiệu quả cao,Ưu tiên mở rộng
2,3,Đại lý | East | Uong Bi | District #09,Đại lý,"39,955,901.77",81.12,Hiệu quả cao,Ưu tiên mở rộng
3,4,Đại lý | West | Long Xuyen | District #39,Đại lý,"34,583,746.97",77.35,Hiệu quả cao,Ưu tiên mở rộng
4,5,Đại lý | East | Bac Ninh | District #03,Đại lý,"29,468,270.21",76.73,Hiệu quả cao,Ưu tiên mở rộng
5,6,Đại lý | Central | Kon Tum | District #24,Đại lý,"34,660,882.37",76.73,Hiệu quả cao,Ưu tiên mở rộng
6,7,Đại lý | East | Ninh Binh | District #03,Đại lý,"30,225,979.48",73.47,Hiệu quả cao,Ưu tiên mở rộng
7,8,Văn phòng | East | Viet Tri | District #19,Văn phòng,"31,757,608.00",73.16,Hiệu quả cao,Ưu tiên mở rộng
8,9,Văn phòng | East | Lao Cai | District #19,Văn phòng,"31,953,442.08",72.24,Hiệu quả cao,Ưu tiên mở rộng
9,10,Đại lý | East | Hanoi | District #11,Đại lý,"35,171,108.23",71.22,Hiệu quả cao,Ưu tiên mở rộng